cciudades_homepage:
    pattern:  /
    defaults: { _controller: cciudadesBundle:Default:home }
cciudades_city:
    pattern:  /city/{id}
    defaults: { _controller: cciudadesBundle:Default:city }
cciudades_countries:
    pattern:  /countries
    defaults: { _controller: cciudadesBundle:Default:paises }
cciudades_pais:
    pattern:  /country/{co}/{inicial}
    defaults: { _controller: cciudadesBundle:Default:pais }
cciudades_search:
    pattern:  /search
    defaults: { _controller: cciudadesBundle:Default:search }
    
cciudades_recibirformulario:
    pattern:  /show
    defaults: { _controller: cciudadesBundle:Default:result }